In [2]:
import pandas as p
data_juegos = p.read_csv("juegos-ml.csv")
X = data_juegos.drop(columns=["juegos"]) # Input
y = data_juegos["juegos"] # Output
data_juegos

    edad  genero      juegos
0      8       0      accion
1     11       0      accion
2     12       0         fps
3     13       0         fps
4     15       0         fps
5     18       0         fps
6     22       0        jrpg
7     25       0        jrpg
8     28       0        jrpg
9     31       0      accion
10    32       0      accion
11    35       0      accion
12    10       1  plataforma
13    13       1  plataforma
14    14       1  plataforma
15    15       1      puzzle
16    18       1      puzzle
17    19       1         fps
18    22       1         fps
19    25       1         fps

In [2]:
from sklearn.tree import DecisionTreeClassifier
modelo = DecisionTreeClassifier()
modelo.fit(X.values, y)
predicciones = modelo.predict([[14,0]])
predicciones

NameError: name 'X' is not defined